### PR TITLE
Add vboxfs issue / guest extensions troubleshooting item

### PR DESCRIPTION
**Pull request by timcharper**

### CODE REVIEW

**Comment by timcharper** [comment]
So, after doing this, it still doesn't work.

I am using Virtualbox `5.1.x`; the trouble is is that the referenced virtualbox image:

1. has an old kernel, so vagrant vb guest plugin does not work
1. has old guest additions

A newer image should help.

**Comment by karlkfi** [comment]
@timcharper Did it actually say...

```
vboxfs file system not available
```

or did it say...

```
==> a1: Machine booted and ready! 
==> a1: Checking for guest additions in VM... 
a1: The guest additions on this VM do not match the installed version of 
a1: VirtualBox! In most cases this is fine, but in rare cases it can 
a1: prevent things such as shared folders from working properly. If you see 
a1: shared folder errors, please make sure the guest additions within the 
a1: virtual machine match the version of VirtualBox you have installed on 
a1: your host and reload your VM. 
a1: 
a1: Guest Additions Version: 5.0.20 
a1: VirtualBox Version: 5.1 
==> a1: Setting hostname... 
==> a1: Configuring and enabling network interfaces... 
==> a1: Mounting shared folders... 
a1: /vagrant => /data2/tmarble/src/github/dcos/dcos-vagrant 
Vagrant was unable to mount VirtualBox shared folders. This is usually 
because the filesystem "vboxsf" is not available. This filesystem is 
made available via the VirtualBox Guest Additions and kernel module. 
Please verify that these guest additions are properly installed in the 
guest. This is not a bug in Vagrant and is usually caused by a faulty 
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=501,gid=501 vagrant /vagrant

The error output from the command was: /sbin/mount.vboxsf: mounting failed with the error: No such device <device name>
```

**Comment by timcharper** [comment]
the latter

**Comment by timcharper** [comment]
I'll fix it

**Comment by windus** [comment]
I'm finding the same issue...with Vagrant 1.9.1 and 1.9.0.  Is anyone able to suggest a fix?

**Comment by karlkfi** [comment]
@windus: `vagrant plugin uninstall vagrant-vbguest`

The current version of the vagrant-vbguest plugin is broken and does not support CentOS 7.2 images.

**Comment by windus** [comment]
Thanks for the clarification.  I'll switch out the OS version then.

**Comment by karlkfi** [comment]
Uh, no. That would require a new dcos-vagrant-box image to be built.

**Comment by windus** [comment]
In the end, I switched to precise64 and adjusted a few other things.  I was only prototyping something so I just gave up on my previous approach.

**Comment by luisdavim** [comment]
this could help:
https://github.com/dotless-de/vagrant-vbguest/issues/117#issuecomment-41927201

**Comment by msabramo** [comment]
👍 

I had the same problem and that's what I did to work around it.

**Comment by RogerWeihrauch** [comment]
.. and further on no success in mounting the vboxsf:
----------------------------------------------------
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=501,gid=501 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
------------------------------------------------------------------

Regards,
Roger

**Comment by karlkfi** [comment]
I'm not going to hack dcos-vagrant to monkeypatch the vagrant-vbguest plugin. If you want to use dcos-vagrant you must uninstall vagrant-vbguest. Otherwise you're on your own to figure out a hack.

**Comment by jackyq2015** [comment]
@karlkfi Uninstall vbguest won't work either when do:
`mount -t vboxsf -o uid=501,gid=501 vagrant /vagrant`
My understanding is that dcos-vagrant-box image have 2 kernel: 3.10.0-327.36.1.el7.x86_64 and 3.10.0-514.10.2.el7.x86_64:
```
[root@a1 ~]# rpm -qa |grep kernel | sort
kernel-3.10.0-327.36.1.el7.x86_64
kernel-3.10.0-514.10.2.el7.x86_64
kernel-devel-3.10.0-514.10.2.el7.x86_64
kernel-headers-3.10.0-514.10.2.el7.x86_64
kernel-tools-3.10.0-514.10.2.el7.x86_64
kernel-tools-libs-3.10.0-514.10.2.el7.x86_64
```
which confuse the vbguest since the running kernel 3.10.0-327.36.1.el7.x86_64 does not have the kernel-headers but the newer version kernel-3.10.0-514.10.2.el7.x86_64 does have. The VBoxAddition need the header to do make. 

I manually ssh into the box and upgraded the kernel to 3.10.0-514 and run vagrant vbguest, then works:
```
yum install grub2
yum reinstall kernel-3.10.0-514.10.2.el7.x86_64
```

**Comment by karlkfi** [comment]
The latest dcos-vagrant-box uses CentOS 7.3. So this should no longer be an issue.

**Comment by timcharper** [comment]
I can confirm this to be the case; I've successfully provisioned a cluster with the latest dcos-vagrant while the vbguest plugin was installed.

**Pull request closed without merging**
