### PR TITLE
Support download of installer using CA_CERT_BUNDLE

### PR DESCRIPTION
**Pull request by jongiddy**
The installer script download within the dcos-vagrant Vagrantfile does not allow setting any CA certificate options. This prevents the Vagrantfile working behind an SSL-intercepting proxy.

This PR sets the `ca_cert` option from the `CURL_CA_BUNDLE` environment variable if it is set. This should support most scenarios where the default CA list is not correct.

This fixes the issue described in [DCOS_VAGRANT-59](https://jira.mesosphere.com/browse/DCOS_VAGRANT-59), except that it does not support setting the `insecure` option. The `insecure` option is a simpler but less secure solution to untrusted CA certificates. Use of `--insecure` can usually be handled better using `--ca_cert`.

As an alternative, we could also use the `SSL_CERT_FILE` environment variable used by Ruby `net/http`, but Vagrant uses cURL for downloads, so `CURL_CA_BUNDLE` seems like the appropriate variable to follow.

### CODE REVIEW

**Comment by karlkfi** [comment]
Would you add a line to the configuration options section, please? 
https://github.com/dcos/dcos-vagrant/blob/master/docs/configure.md

**Comment by jongiddy** [comment]
I added the line to the proxy section, since this is the most likely reason to need to use the `CURL_CA_BUNDLE` variable. Hope this is OK.

I also removed the line about https -> http as it is quite common to connect HTTPS connections through a HTTP proxy. The connection is insecure within the local network, but will create a secure tunnel from the proxy to the HTTPS endpoint.

And a minor spelling correction as well.

**Comment by karlkfi** [comment]
I was thinking more specifically it should be in the master list of env vars (or maybe both places?): https://github.com/dcos/dcos-vagrant/blob/master/docs/configure.md#environment-options

**Comment by jongiddy** [comment]
Done. I'd like to keep the other text to demonstrate when to use it.

**Comment by karlkfi** [comment]
thanks!

**Pull request merged**
